/*
Package kubeclient GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package kubeclient

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}

func (v KubeClient) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "Kubeconfig":
			return []string{
				"Paths to a kubeconfig. Only required if out-of-cluster.",
			}, true
		}

		return nil, false
	}
	return []string{}, true
}
