/*
Package crd GENERATED BY gengo:runtimedoc
DON'T EDIT THIS FILE
*/
package crd

func (v *CustomResourceDefinition) RuntimeDoc(names ...string) ([]string, bool) {
	if len(names) > 0 {
		switch names[0] {
		case "GroupVersion":
			return []string{}, true
		case "KindType":
			return []string{}, true
		case "ListKindType":
			return []string{}, true
		case "SpecType":
			return []string{}, true
		case "Plural":
			return []string{}, true
		case "ShortNames":
			return []string{}, true

		}

		return nil, false
	}
	return []string{}, true
}

// nolint:deadcode,unused
func runtimeDoc(v any, prefix string, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		doc, ok := c.RuntimeDoc(names...)
		if ok {
			if prefix != "" && len(doc) > 0 {
				doc[0] = prefix + doc[0]
				return doc, true
			}

			return doc, true
		}
	}
	return nil, false
}
