/*
Package metadata GENERATED BY gengo:runtimedoc 
DON'T EDIT THIS FILE
*/
package metadata

// nolint:deadcode,unused
func runtimeDoc(v any, names ...string) ([]string, bool) {
	if c, ok := v.(interface {
		RuntimeDoc(names ...string) ([]string, bool)
	}); ok {
		return c.RuntimeDoc(names...)
	}
	return nil, false
}

func (Annotation) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (Label) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
func (Scope) RuntimeDoc(names ...string) ([]string, bool) {
	return []string{}, true
}
